DesenvolvimentoWeb/AplicacaoFinanceiraCursoAlgaWorks/src/br/nom/brunokarpo/financeiro/managedBeans/CadastroLancamentoBean.java
package br.nom.brunokarpo.financeiro.managedBeans;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;

import br.nom.brunokarpo.financeiro.entidades.Lancamento;
import br.nom.brunokarpo.financeiro.entidades.Pessoa;
import br.nom.brunokarpo.financeiro.entidades.TipoLancamento;
import br.nom.brunokarpo.financeiro.negocio.GestaoLancamento;
import br.nom.brunokarpo.financeiro.negocio.RegraNegocioException;
import br.nom.brunokarpo.financeiro.repository.Lancamentos;
import br.nom.brunokarpo.financeiro.repository.Pessoas;
import br.nom.brunokarpo.financeiro.repository.Repositorios;

@ManagedBean
public class CadastroLancamentoBean implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	private Lancamento lancamento;

	@PostConstruct
	public void iniciar() {
		this.lancamento = new Lancamento();
	}

	public TipoLancamento[] getTiposLancamentosPossiveis() {
		return TipoLancamento.values();
	}
	@SuppressWarnings("unchecked")
	public List<Pessoa> getPessoas() {
		Pessoas pessoas = Repositorios.getRepositorios().getPessoas();

		return pessoas.todas();
	}

	public void lancamentoPagoModificado(ValueChangeEvent event) {
		this.lancamento.setPago((Boolean) event.getNewValue());
		this.lancamento.setDataPagamento(null);
		FacesContext.getCurrentInstance().renderResponse();
	}

	public void salvar() {
		GestaoLancamento service = new GestaoLancamento();

		try {
			service.salvarLancamento(this.lancamento);

			FacesUtil.adicionarMensagem(FacesMessage.SEVERITY_INFO, "Lançamento salvo com sucesso");
			this.lancamento = new Lancamento();
		} catch (RegraNegocioException e) {
			FacesUtil.adicionarMensagem(FacesMessage.SEVERITY_ERROR, e.getMessage());
		}

	}

	public Lancamento getLancamento() {
		return this.lancamento;
	}

	public void setLancamento(Lancamento lancamento) throws CloneNotSupportedException {
		this.lancamento = lancamento;
		if(this.lancamento == null) {
			this.lancamento = new Lancamento();
		} else {
			this.lancamento = (Lancamento) lancamento.clone();
		}
	}

	public boolean isNovoLancamento() {
		if(this.lancamento.getCodigo() == null) {
			return true;
		}
		return false;
	}
}

DesenvolvimentoWeb/AplicacaoFinanceiraCursoAlgaWorks/src/br/nom/brunokarpo/financeiro/managedBeans/ConsultaLancamentosBean.java
package br.nom.brunokarpo.financeiro.managedBeans;

import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;

import br.nom.brunokarpo.financeiro.entidades.Lancamento;
import br.nom.brunokarpo.financeiro.negocio.GestaoLancamento;
import br.nom.brunokarpo.financeiro.negocio.RegraNegocioException;
import br.nom.brunokarpo.financeiro.repository.Lancamentos;
import br.nom.brunokarpo.financeiro.repository.Repositorios;

@ManagedBean
public class ConsultaLancamentosBean implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Lancamento lancamentoSelecionado;

	@SuppressWarnings("unchecked")
	public List<Lancamento> getLancamentos() {
		Lancamentos lancamentos = Repositorios.getRepositorios().getLancamentos();

		return lancamentos.todos();
	}

	public void excluir() {
		GestaoLancamento service = new GestaoLancamento();

		try {
			service.excluirLancamento(this.lancamentoSelecionado);

			FacesUtil.adicionarMensagem(FacesMessage.SEVERITY_INFO, "Lançamento excluído com sucesso");
			FacesContext.getCurrentInstance().renderResponse();
		} catch (RegraNegocioException e) {
			FacesUtil.adicionarMensagem(FacesMessage.SEVERITY_ERROR, e.getMessage());
		}

	}

	public Lancamento getLancamentoSelecionado() {
		return lancamentoSelecionado;
	}
	public void setLancamentoSelecionado(Lancamento lancamentoSelecionado) {
		this.lancamentoSelecionado = lancamentoSelecionado;
	}

}

DesenvolvimentoWeb/AplicacaoFinanceiraCursoAlgaWorks/WebContent/pages/CadastroLancamento.xhtml
<ui:composition template="/pages/template/LayoutPadrao.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets" >

	<ui:define name="titulo">#{cadastroLancamentoBean.novoLancamento ? i18n['new_entry'] : i18n['edit_entry']}</ui:define>

	<ui:define name="conteudo">
		<f:metadata>
			<f:viewParam name="codigo" value="#{cadastroLancamentoBean.lancamento}" />
		</f:metadata>

		<h1>#{cadastroLancamentoBean.novoLancamento ? i18n['new_entry'] : i18n['edit_entry']}</h1>

		<h:form id="frm">

			<h:button value="#{i18n['new']}" outcome="/pages/CadastroLancamento.xhtml" />
			<h:button value="#{i18n['search']}" outcome="/pages/ConsultaLancamentos.xhtml" />

			<h:messages showDetail="true" showSummary="false" styleClass="form-messages"
					infoClass="info" errorClass="error"/>

			<h:panelGrid columns="2" styleClass="form-grid" columnClasses="label, campo" id="panel">

				<h:outputLabel value="#{i18n['label.type']}"/>
				<h:selectOneRadio value="#{cadastroLancamentoBean.lancamento.tipo}" required="true" label="#{i18n['label.entry_type']}">
					<f:selectItems value="#{cadastroLancamentoBean.tiposLancamentosPossiveis}" var="tipoLancamento"
							itemValue="#{tipoLancamento}" itemLabel="#{i18n[tipoLancamento.descricao]}"/>
				</h:selectOneRadio>

				<h:outputLabel value="#{i18n['Person']}"/>
				<h:selectOneMenu value="#{cadastroLancamentoBean.lancamento.pessoa}">
					<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
					<f:selectItems value="#{cadastroLancamentoBean.pessoas}" var="pessoa"
						itemLabel="#{pessoa.nome}" itemValue="#{pessoa}"/>
				</h:selectOneMenu>

				<h:outputLabel value="#{i18n['Detail']}"/>
				<h:inputText size="60" value="#{cadastroLancamentoBean.lancamento.descricao}"
						required="true" label="#{i18n['Detail']}"/>

				<h:outputLabel value="#{i18n['Value']}"/>
				<h:inputText size="12" value="#{cadastroLancamentoBean.lancamento.valor}"
						required="true" label="#{i18n['Value']}" >
					<f:convertNumber locale="pt_BR" minFractionDigits="2" />
					<f:validateDoubleRange minimum="0"/>
				</h:inputText>

				<h:outputLabel value="#{i18n['Due_date']}"/>
				<h:inputText size="12" value="#{cadastroLancamentoBean.lancamento.dataVencimento}"
						required="true" label="#{i18n['Due_date']}">
					<f:convertDateTime pattern="dd/MM/yyyy"/>
				</h:inputText>

				<h:outputLabel />
				<h:panelGroup>
					<h:selectBooleanCheckbox value="#{cadastroLancamentoBean.lancamento.pago}"
							immediate="true" valueChangeListener="#{cadastroLancamentoBean.lancamentoPagoModificado}"
							onchange="jsf.ajax.request(this, event, {execute: '@form', render: 'frm:panel'})"/>
					<h:outputLabel value="#{i18n['paid']}"/>
				</h:panelGroup>

				<h:outputLabel value="#{i18n['Payday']}" rendered="#{cadastroLancamentoBean.lancamento.pago}"/>
				<h:inputText size="12" value="#{cadastroLancamentoBean.lancamento.dataPagamento}"
						label="#{i18n['Payday']}" rendered="#{cadastroLancamentoBean.lancamento.pago}">
					<f:convertDateTime pattern="dd/MM/yyyy"/>
					<f:validator validatorId="nom.brunokarpo.RequeridoCondicional"/>
					<f:validator validatorId="nom.brunokarpo.DataFutura"/>
					<f:attribute name="checado" value="#{cadastroLancamentoBean.lancamento.pago}"/>
				</h:inputText>

				<h:outputLabel />
				<h:commandButton value="#{i18n['save']}" action="#{cadastroLancamentoBean.salvar}">
					<f:ajax execute="@form" render="@all"/>
				</h:commandButton>
			</h:panelGrid>

		</h:form>

	</ui:define>

</ui:composition>

DesenvolvimentoWeb/AplicacaoFinanceiraCursoAlgaWorks/WebContent/pages/ConsultaLancamentos.xhtml
<ui:composition template="/pages/template/LayoutPadrao.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:bk="http://java.sun.com/jsf/composite/brunokarpo">

	<ui:define name="titulo">Lançamentos</ui:define>

	<ui:define name="conteudo">

		<h:outputStylesheet library="css" name="consultas-lancamentos.css"/>

		<h1>#{i18n['entrys']}</h1>

		<h:form id="frm">

			<h:button value="#{i18n['new_entry']}" outcome="/pages/CadastroLancamento.xhtml"/>

			<h:messages showDetail="true" showSummary="false" styleClass="form-messages"
					infoClass="info" errorClass="error"/>

			<h:dataTable value="#{consultaLancamentosBean.lancamentos}" var="lancamento"
					width="100%" headerClass="cabecalho" styleClass="grid" rowClasses="cor-sim, cor-nao"
					columnClasses="tipo, pessoa, descricao, valor, vencimento, pagamento, situacao, acoes">

				<h:column>
					<h:graphicImage value="/imagens/despesa.png" rendered="#{lancamento.tipo eq 'DESPESA'}"/>
					<h:graphicImage value="/imagens/receita.png" rendered="#{lancamento.tipo eq 'RECEITA'}"/>
				</h:column>

				<h:column>
					<f:facet name="header">
						#{i18n['Person']}
					</f:facet>

					<h:outputText value="#{lancamento.pessoa.nome}"/>
				</h:column>

				<h:column>
					<f:facet name="header">
						#{i18n['Detail']}
					</f:facet>

					<h:outputText value="#{lancamento.descricao}"/>
				</h:column>

				<h:column>
					<f:facet name="header">
						#{i18n['Value']}
					</f:facet>

					<bk:outputValorLancamento lancamentoBean="#{lancamento}" />
				</h:column>

				<h:column>
					<f:facet name="header">
						#{i18n['Due_date']}
					</f:facet>

					<h:outputText value="#{lancamento.dataVencimento}">
						<f:convertDateTime pattern="dd/MM/yyyy"/>
					</h:outputText>
				</h:column>

				<h:column>
					<f:facet name="header">
						#{i18n['Payday']}
					</f:facet>

					<h:outputText value="#{lancamento.dataPagamento}">
						<f:convertDateTime pattern="dd/MM/yyyy"/>
					</h:outputText>
				</h:column>

				<h:column>
					<f:facet name="header">
						#{i18n['Situation']}
					</f:facet>

					<h:outputText value="#{i18n['Paid']}" rendered="#{lancamento.pago}"/>
					<h:outputText value="#{i18n['Open']}" rendered="#{not lancamento.pago}"/>
				</h:column>

				<h:column>
					<h:link outcome="CadastroLancamento">
						<h:graphicImage value="/imagens/editar.png" />
						<f:param name="codigo" value="#{lancamento.codigo}" />
					</h:link>

					<h:commandLink action="#{consultaLancamentosBean.excluir}">
						<h:graphicImage value="/imagens/excluir.png" />
						<f:setPropertyActionListener value="#{lancamento}" target="#{consultaLancamentosBean.lancamentoSelecionado}" />
						<f:ajax render="@form"/>
					</h:commandLink>
				</h:column>

			</h:dataTable>

		</h:form>
	</ui:define>

</ui:composition>

DesenvolvimentoWeb/AplicacaoFinanceiraCursoAlgaWorks/WebContent/pages/Home.xhtml
<ui:composition template="/pages/template/LayoutPadrao.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<ui:define name="conteudo">
		<h2 style="text-align: center; padding: 100px">#{i18n['welcome']}</h2>
	</ui:define>

</ui:composition>

DesenvolvimentoWeb/AplicacaoFinanceiraCursoAlgaWorks/WebContent/pages/template/Cabecalho.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<h:graphicImage value="/imagens/logo.png" styleClass="logo"/>
	<div class="menu">
		<h:link outcome="/pages/Home">#{i18n['home']}</h:link>
		<h:link outcome="/pages/ConsultaLancamentos">#{i18n['entrys']}</h:link>
	</div>

</ui:composition>

DesenvolvimentoWeb/AplicacaoFinanceiraCursoAlgaWorks/WebContent/pages/template/LayoutPadrao.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title><ui:insert name="titulo">Financeiro</ui:insert></title>

		<h:outputStylesheet library="css" name="sistema.css"/>
	</h:head>
	<h:body>
		<div id="header">
			<ui:insert name="cabecalho">
				<ui:include src="/pages/template/Cabecalho.xhtml" />
			</ui:insert>
		</div>

		<div id="content">
			<ui:insert name="conteudo"/>
		</div>

		<div id="footer">
			<ui:insert name="rodape">
				<ui:include src="/pages/template/Rodape.xhtml" />
			</ui:insert>
		</div>
	</h:body>
</html>

DesenvolvimentoWeb/AplicacaoFinanceiraCursoAlgaWorks/WebContent/pages/template/Rodape.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	#{i18n['footer.msg']}
	<br/><h:outputLink outcome="www.algaworks.com.br">www.algaworks.com.br</h:outputLink>

</ui:composition>

DesenvolvimentoWeb/AplicacaoFinanceiraCursoAlgaWorks/WebContent/resources/brunokarpo/outputCurrency.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:composite="http://java.sun.com/jsf/composite">

	<composite:interface>
		<composite:attribute name="value" required="true"/>
		<composite:attribute name="locale" default="pt_BR" />
		<composite:attribute name="currencySymbol" default="R$" />
		<composite:attribute name="styleClass" />
	</composite:interface>

	<composite:implementation>
		<h:outputText value="#{cc.attrs.value}" styleClass="#{cc.attrs.styleClass}">
			<f:convertNumber locale="#{cc.attrs.locale}" currencySymbol="#{cc.attrs.currencySymbol}"
					type="currency"/>
		</h:outputText>
	</composite:implementation>
</html>

DesenvolvimentoWeb/AplicacaoFinanceiraCursoAlgaWorks/WebContent/resources/brunokarpo/outputValorLancamento.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:composite="http://java.sun.com/jsf/composite">

	<composite:interface>
		<composite:attribute name="lancamentoBean" required="true"/>
		<composite:attribute name="locale" default="pt_BR" />
		<composite:attribute name="currencySymbol" default="R$" />
	</composite:interface>

	<composite:implementation>
		<h:outputText value="#{cc.attrs.lancamentoBean.valor}"
				styleClass="#{cc.attrs.lancamentoBean.tipo.toString().toLowerCase()}">
			<f:convertNumber locale="#{cc.attrs.locale}" currencySymbol="#{cc.attrs.currencySymbol}"
					type="currency"/>
		</h:outputText>
	</composite:implementation>
</html>